CREATE DATABASE SushiDB
--DROP DATABASE SushiDB

GO
USE SushiDB
GO

CREATE TABLE HOADON
(
    MAHOADON CHAR(10),
    GIOLAP TIME,
    NGAYLAP DATE,
    VAT FLOAT,
    TIENKHACHDUA FLOAT,
    TRANGTHAI NVARCHAR(20),
    PHUONGTHUC NVARCHAR(20),
    BACTHETHANHVIEN CHAR(10),
    MAKHUYENMAI CHAR(10),
	TONGTIEN FLOAT, -- thuộc tính suy diễn từ DONGIATONG (CHITIETMONAN), VAT (HOADON), LUONGKMPHANTRAM (KHUYENMAI) từ các HOADONLIENQUAN (DONDATMON)
					-- TONGTIEN = SUM(THANHTIEN) x (1 + VAT) x (1 - LUONGKMPHANTRAM)

	CONSTRAINT PK_HOADON
    PRIMARY KEY (MAHOADON)
)

CREATE TABLE DONDATMON
(
    MADON CHAR(10),
    GIODAT TIME,
    NGAYDAT DATE,
    TRANGTHAI NVARCHAR(20),
	LOAIDONDATMON NVARCHAR(20),
    HOADONLIENQUAN CHAR(10),
    KHACHHANGDAT CHAR(10),
    MADATCHO CHAR(10),
    CHINHANHDAT CHAR(10), 
    NHANVIENTAOLAP CHAR(10),
	THANHTIEN FLOAT,	-- thuộc tính suy diễn từ DONGIATONG (CHITIETMONAN)
						-- THANHTIEN = SUM(DONGIATONG)

    CONSTRAINT PK_DONDATMON
    PRIMARY KEY (MADON)
)

CREATE TABLE DATHANGTRUCTUYEN
(
    MADHTRUCTUYEN CHAR(10),
    THOIGIANGIAO TIME,
    DIACHIGIAO NVARCHAR(100),
    TRANGTHAIGIAO NVARCHAR(20),

    CONSTRAINT PK_DATHANGTRUCTUYEN
    PRIMARY KEY (MADHTRUCTUYEN)
)

CREATE TABLE DATHANGTAICHO
(
    MADHTAICHO CHAR(10),
    MACHINHANH CHAR(10),
    SOBAN VARCHAR(3),

    CONSTRAINT PK_DATHANGTAICHO
    PRIMARY KEY (MADHTAICHO)
)

CREATE TABLE CHINHANH
(
	MACHINHANH CHAR(10),
	TENCHINHANH NVARCHAR(50),
	DIACHI NVARCHAR(100),
	KHUVUC NVARCHAR(50),
	THOIGIANMOCUA TIME,
	THOIGIANDONGCUA TIME,
	SDT CHAR(10) CHECK (LEN(SDT)=10 AND SDT NOT LIKE '%[^0-9]%'),
	COBAIDOXE BIT,
	NHANVIENQUANLY CHAR(10),
	DOANHTHUCHINHANH FLOAT, -- thuộc tính suy diễn từ TONGTIEN (HOADON) theo CHINHANHDAT(DONDATMON)
							-- DOANHTHUCHINHANH = SUM(TONGTIEN)
	
	CONSTRAINT PK_CHINHANH
	PRIMARY KEY (MACHINHANH)
)

CREATE TABLE BANAN
(
	SOBAN VARCHAR(3) CHECK (SOBAN NOT LIKE '%[^0-9]%'),
	MACHINHANH CHAR(10),
	VITRI NVARCHAR(50),
	TRANGTHAI NVARCHAR(20),
	SONGUOITOIDA INT,

	CONSTRAINT PK_BANAN
	PRIMARY KEY (SOBAN, MACHINHANH)
)

CREATE TABLE DATCHO
(
	MADATCHO CHAR(10),
	NGAYDEN DATE,
	GIODEN TIME,
	SOLUONGKHACH INT, -- thuộc tính suy diễn từ SOLUONGKHACH (CHITIETDATCHO)
					  -- SOLUONGKHACH = SUM(SOLUONGKHACH)
	GHICHU NVARCHAR(MAX),
	SDT CHAR(10) CHECK (LEN(SDT)=10 AND SDT NOT LIKE '%[^0-9]%'),

	CONSTRAINT PK_DATCHO
	PRIMARY KEY (MADATCHO)
)

CREATE TABLE CHITIETDATCHO
(
	SOBAN VARCHAR(3),
	MACHINHANH CHAR(10),
	MADATCHO CHAR(10),
	SOLUONGKHACH INT,

	CONSTRAINT PK_CHITIETDATCHO
	PRIMARY KEY (SOBAN, MACHINHANH, MADATCHO)
)

CREATE TABLE NHANVIEN
(
	MANHANVIEN CHAR(10),
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH IN ('NAM','NỮ')),
	SDT CHAR(10) CHECK (LEN(SDT)=10 AND SDT NOT LIKE '%[^0-9]%'),
	DIACHI NVARCHAR(100),
	CHINHANHLAMVIEC CHAR(10),
	LUONGHIENTAI FLOAT, -- thuộc tính suy diễn từ LUONG (BOPHAN) và HESOLUONG (LICHSULAMVIEC) của công việc gần nhất
						-- LUONGHIENTAI = LUONG * HESOLUONG
	
	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY (MANHANVIEN)
)

CREATE TABLE BOPHAN
(
	MABOPHAN CHAR(10),
	MACHINHANH CHAR(10),
	TENBOPHAN NVARCHAR(50),
	LUONG FLOAT,
	QUANLYBOPHAN CHAR(10),

	CONSTRAINT PK_BOPHAN
	PRIMARY KEY (MABOPHAN, MACHINHANH)
)

CREATE TABLE LICHSULAMVIEC
(
	MANHANVIEN CHAR(10),
	MABOPHAN CHAR(10),
	MACHINHANH CHAR(10),
	NGAYVAOLAM DATE,
	NGAYNGHIVIEC DATE,
	HESOLUONG FLOAT,

	CONSTRAINT PK_LICHSULAMVIEC
	PRIMARY KEY (MANHANVIEN, MABOPHAN, MACHINHANH)
)

CREATE TABLE KHACHHANG
(
	MAKHACHHANG CHAR(10),
	HOTEN NVARCHAR(50),
	SDT CHAR(10) CHECK (LEN(SDT)=10 AND SDT NOT LIKE '%[^0-9]%'),
	EMAIL VARCHAR(30),
	CCCD VARCHAR(20),

	CONSTRAINT PK_KHACHHANNG
	PRIMARY KEY (MAKHACHHANG)
)

CREATE TABLE DANHGIA
(
	MADANHGIA CHAR(10),
	DIEMPHUCVU INT,
	DIEMVITRICHINHANH INT,
	DIEMKHONGGIAN INT,
	BINHLUAN NVARCHAR(400),
	KHACHHANGDANHGIA CHAR(10),
	CHINHANH CHAR(10),
	NHANVIEN CHAR(10),

	CONSTRAINT PK_DANHGIA
	PRIMARY KEY (MADANHGIA)
)

CREATE TABLE THETHANHVIEN
(
	MATHE CHAR(10),
	LOAITHE NVARCHAR(50),

	CONSTRAINT PK_THETHANHVIEN
	PRIMARY KEY (MATHE)
)

CREATE TABLE CHITIETKHACHHANG
(
	MAKHACHHANG CHAR(10),
	MATHE CHAR(10),
	NGAYDK DATE,
	DIEMTICHLUY INT,
	NGAYNANGHANG DATE,
	TRANGTHAITAIKHOAN NVARCHAR(50),
	NHANVIENTAOLAP CHAR(10),

	CONSTRAINT PK_CHITIETKHACHHAHG
	PRIMARY KEY (MAKHACHHANG, MATHE)
)

CREATE TABLE DANHGIAMONAN
(
	MADANHGIA CHAR(10),
	MAMON CHAR(10),
	DIEMCHATLUONGMONAN INT,
	DIEMGIACA INT,

	CONSTRAINT PK_DANHGIAMONAN
	PRIMARY KEY (MADANHGIA, MAMON)
)

CREATE TABLE TRUYCAP
(
	MATRUYCAP CHAR(10),
	MADANHGIA CHAR(10),
	THOIDIEMBATDAU DATE,
	THOIDIEMKETTHUC DATE,

	CONSTRAINT PK_TRUYCAP
	PRIMARY KEY (MATRUYCAP, MADANHGIA)
)

CREATE TABLE MONAN
(
	MAMON CHAR(10),
	TENMON NVARCHAR(50),
	GIAHIENTAI FLOAT,
	DANHMUC NVARCHAR(50),

	CONSTRAINT PK_MONAN
	PRIMARY KEY (MAMON)
)

CREATE TABLE COMBOMONAN
(
	MACOMBO CHAR(10),
	TENCOMBO NVARCHAR(50),
	MOTACOMBO NVARCHAR(MAX),
	DONGIACOMBO FLOAT,

	CONSTRAINT PK_COMBOMONAN
	PRIMARY KEY (MACOMBO)
)

CREATE TABLE CHITIETMONAN
(
	MACTMON CHAR(10),
	MAMON CHAR(10),
	MACOMBO CHAR(10),
	SOLUONG INT,
	GHICHU NVARCHAR(MAX),
	DONGIATONG FLOAT,
	MADONDATMON CHAR(10),

	CONSTRAINT PK_CHITIETMONAN
	PRIMARY KEY (MACTMON)
)

CREATE TABLE MONAN_COMBOMONAN
(
	MACOMBO CHAR(10),
	MAMON CHAR(10),
	SOLUONG INT,

	CONSTRAINT PK_MONAN_COMBOMONAN
	PRIMARY KEY (MACOMBO, MAMON)
)

CREATE TABLE KHUYENMAI
(
	MAKHUYENMAI CHAR(10),
	THONGTINKHUYENMAI NVARCHAR(MAX),
	LUONGKMPHANTRAM FLOAT,
	LOAIKHUYENMAI NVARCHAR(20),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,

	CONSTRAINT PK_KHUYENMAI
	PRIMARY KEY (MAKHUYENMAI)
)

CREATE TABLE KHUYENMAIKHACHHANG
(
	MAKHUYENMAI CHAR(10),
	TRANGTHAIDUNG BIT,
	MAKHACHHANG CHAR(10),

	CONSTRAINT PK_KHUYENMAIKHACHHANG
	PRIMARY KEY (MAKHUYENMAI)
)

CREATE TABLE KHUYENMAITHETHANHVIEN
(
	MAKHUYENMAI CHAR(10),
	MATHE CHAR(10),

	CONSTRAINT PK_KHUYENMAITHETHANHVIEN
	PRIMARY KEY (MAKHUYENMAI)
)

ALTER TABLE HOADON
ADD
	CONSTRAINT FK_HOADON_THE
	FOREIGN KEY (BACTHETHANHVIEN)
	REFERENCES THETHANHVIEN(MATHE),

	CONSTRAINT FK_HOADON_KHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI)

ALTER TABLE DONDATMON
ADD
	CONSTRAINT FK_DONDATMON_HOADON
	FOREIGN KEY (HOADONLIENQUAN)
	REFERENCES HOADON(MAHOADON)
	ON DELETE SET NULL,

	CONSTRAINT FK_DONDATMON_KHACHHANG
	FOREIGN KEY (KHACHHANGDAT)
	REFERENCES KHACHHANG(MAKHACHHANG),

    CONSTRAINT FK_DONDATMON_DATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO),

    CONSTRAINT FK_DONDATMON_CHINHANH
	FOREIGN KEY (CHINHANHDAT)
	REFERENCES CHINHANH(MACHINHANH),

	CONSTRAINT FK_DONDATMON_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE DATHANGTRUCTUYEN
ADD
    CONSTRAINT FK_DATHANGTRUCTUYEN_DONDATMON
    FOREIGN KEY (MADHTRUCTUYEN)
    REFERENCES DONDATMON(MADON)

ALTER TABLE DATHANGTAICHO
ADD
    CONSTRAINT FK_DATHANGTAICHO_DONDATMON
    FOREIGN KEY (MADHTAICHO)
    REFERENCES DONDATMON(MADON),

    CONSTRAINT PK_DATHANGTAICHO_BANAN
    FOREIGN KEY (SOBAN, MACHINHANH)
    REFERENCES BANAN(SOBAN, MACHINHANH)

ALTER TABLE CHITIETKHACHHANG
ADD
	CONSTRAINT FK_CHITIETKHACHHANG_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG),

	CONSTRAINT FK_CHITIETKHACHHANG_THETHANHVIEN
	FOREIGN KEY (MATHE)
	REFERENCES THETHANHVIEN(MATHE),

	CONSTRAINT FK_CHITIETKHACHHANG_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE DANHGIAMONAN
ADD
	CONSTRAINT FK_DANHGIAMONAN_DANHGIA
	FOREIGN KEY (MADANHGIA)
	REFERENCES DANHGIA(MADANHGIA),

	CONSTRAINT FK_DANHGIAMONAN_MONAN
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)

ALTER TABLE CHINHANH
ADD
	CONSTRAINT FK_CHINHANH_NHANVIENQUANLY
	FOREIGN KEY (NHANVIENQUANLY)
	REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE BANAN
ADD
	CONSTRAINT FK_BANAN_MACHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)

ALTER TABLE CHITIETDATCHO
ADD
	CONSTRAINT FK_CHITIETDATCHO_SOBAN_MACHINHANH
	FOREIGN KEY (SOBAN, MACHINHANH)
	REFERENCES BANAN(SOBAN, MACHINHANH),

	CONSTRAINT FK_CHITIETDATCHO_MADATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO)

ALTER TABLE NHANVIEN
ADD
	CONSTRAINT FK_NHANVIEN_CHINHANH
	FOREIGN KEY (CHINHANHLAMVIEC)
	REFERENCES CHINHANH(MACHINHANH)

ALTER TABLE BOPHAN
ADD
	CONSTRAINT FK_BOPHAN_CHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH),

	CONSTRAINT FK_BOPHAN_NHANVIEN
	FOREIGN KEY (QUANLYBOPHAN)
	REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE LICHSULAMVIEC
ADD
	CONSTRAINT FK_LICHSULAMVIEC_BOPHAN
	FOREIGN KEY (MABOPHAN, MACHINHANH)
	REFERENCES BOPHAN(MABOPHAN, MACHINHANH),

	CONSTRAINT FK_LICHSULAMVIEC_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE DANHGIA
ADD
	CONSTRAINT FK_DANHGIA_KHACHHANG
	FOREIGN KEY (KHACHHANGDANHGIA)
	REFERENCES KHACHHANG(MAKHACHHANG),

	CONSTRAINT FK_DANHGIA_CHINHANH
	FOREIGN KEY (CHINHANH)
	REFERENCES CHINHANH(MACHINHANH),

	CONSTRAINT FK_DANHGIA_NHANVIEN
	FOREIGN KEY (NHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE DANHGIAMONAN
ADD
	CONSTRAINT FK_DANHGIAMONAN_MADANHGIA
	FOREIGN KEY (MADANHGIA)
	REFERENCES DANHGIA(MADANHGIA),

	CONSTRAINT FK_DANHGIAMONAN_MAMON
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)

ALTER TABLE CHITIETMONAN
ADD
	CONSTRAINT FK_CHITIETMONAN_MAMON
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE,

	CONSTRAINT FK_CHITIETMONAN_MACOMBO
	FOREIGN KEY (MACOMBO)
	REFERENCES COMBOMONAN(MACOMBO)
	ON DELETE CASCADE

ALTER TABLE MONAN_COMBOMONAN
ADD
	CONSTRAINT FK_MONAN_COMBOMONAN_MACOMBO
	FOREIGN KEY (MACOMBO)
	REFERENCES COMBOMONAN(MACOMBO),

	CONSTRAINT FK_MONAN_COMBOMONAN_MAMON
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)

ALTER TABLE KHUYENMAIKHACHHANG
ADD
	CONSTRAINT FK_KHUYENMAIKHACHHANG_MAKHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI),

	CONSTRAINT FK_KHUYENMAIKHACHHANG_MAKHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)

ALTER TABLE KHUYENMAITHETHANHVIEN
ADD
	CONSTRAINT FK_KHUYENMAITHETHANHVIEN_MAKHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI),

	CONSTRAINT FK_KHUYENMAITHETHANHVIEN_MATHE
	FOREIGN KEY (MATHE)
	REFERENCES THETHANHVIEN(MATHE)

ALTER TABLE TRUYCAP
ADD 
	CONSTRAINT FK_TRUYCAP_MADANHGIA
	FOREIGN KEY (MADANHGIA)
	REFERENCES DANHGIA(MADANHGIA)