CREATE DATABASE SushiDB
-- DROP DATABASE SushiDB

GO
USE SushiDB
GO

-- Hoá đơn định danh bởi mã hoá đơn
CREATE TABLE HOADON
(
    MAHOADON CHAR(10),
    GIOLAP TIME NOT NULL,
    NGAYLAP DATE NOT NULL,
    VAT FLOAT DEFAULT 0.08,
    TIENKHACHDUA FLOAT NOT NULL,
    TRANGTHAI NVARCHAR(20) NOT NULL CHECK (TRANGTHAI IN (N'Unpaid', N'Paid', N'Cancelled')),
    PHUONGTHUC NVARCHAR(20) NOT NULL CHECK (PHUONGTHUC IN (N'Bank transfer', N'Cash', N'Credit card')),
    MAKHACHHANG CHAR(10),
	MACHINHANH CHAR(10),
	TONGTIENTRUOCKM FLOAT, -- Thuộc tính suy diễn từ THANHTIEN(DONDATMON), VAT(HOADON) từ các HOADONLIENQUAN (DONDATMON) có TRANGTHAI (DONDATMON) thành công
						   -- TONGTIENTRUOCKM = SUM(THANHTIEN) x (1 + VAT)
	TONGTIENSAUKM FLOAT, -- Thuộc tính suy diễn từ TONGTIENTRUOCKM (HOADON), LUONGKMPHANTRAM (KHUYENMAITHETHANHVIEN), LUONGKMTIEN (KHUYENMAIKHACHHANG)
						 -- TONGTIENSAUKM = (TONGTIENTRUOCKM - LUONGTIENKM) x (1 - LUONGKMPHANTRAM)
	
	CONSTRAINT PK_HOADON
    PRIMARY KEY (MAHOADON)
)

-- Đơn đặt món định danh bởi mã đơn
-- Đơn đặt món chứa các món được đặt và có thể có nhiều đơn đặt món trong hoá đơn
CREATE TABLE DONDATMON
(
    MADON CHAR(10),
    GIODAT TIME NOT NULL,
    NGAYDAT DATE NOT NULL,
    TRANGTHAI NVARCHAR(20) NOT NULL CHECK (TRANGTHAI IN (N'Unconfirmed', N'Processing', N'Successful', N'Paid')),
    LOAIDONDATMON NVARCHAR(20) NOT NULL CHECK (LOAIDONDATMON IN (N'Online order', N'In-store order')),
    HOADONLIENQUAN CHAR(10),
    KHACHHANGDAT CHAR(10),
    MADATCHO CHAR(10) NOT NULL,
    CHINHANHDAT CHAR(10) NOT NULL, 
    NHANVIENTAOLAP CHAR(10),
	THANHTIEN FLOAT,	-- Thuộc tính suy diễn từ DONGIATONG (CHITIETMONAN)
						-- THANHTIEN = SUM(DONGIATONG)
	
    CONSTRAINT PK_DONDATMON
    PRIMARY KEY (MADON)
)

-- Đặt hàng trực tuyến định danh bởi mã đơn hàng trực tuyến
-- Đặt hàng trực tuyến là con của đơn đặt món
CREATE TABLE DATHANGTRUCTUYEN
(
    MADHTRUCTUYEN CHAR(10),
    THOIGIANGIAO TIME NOT NULL,
    DIACHIGIAO NVARCHAR(100) NOT NULL,
    TRANGTHAIGIAO NVARCHAR(20) NOT NULL CHECK (TRANGTHAIGIAO IN (N'Processing', N'Delivered', N'Cancelled')),

    CONSTRAINT PK_DATHANGTRUCTUYEN
    PRIMARY KEY (MADHTRUCTUYEN)
)

-- Đặt hàng tại chỗ định danh bởi mã đơn hàng tại chỗ
-- Đặt hàng tại chỗ là con của đơn đặt món
CREATE TABLE DATHANGTAICHO
(
    MADHTAICHO CHAR(10),
    MACHINHANH CHAR(10),
    SOBAN VARCHAR(3),

    CONSTRAINT PK_DATHANGTAICHO
    PRIMARY KEY (MADHTAICHO)
)

-- Chi nhánh định danh bởi mã chi nhánh
CREATE TABLE CHINHANH
(
	MACHINHANH CHAR(10),
	TENCHINHANH NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	KHUVUC NVARCHAR(50) NOT NULL CHECK (KHUVUC IN (N'District 1', N'District 2', N'District 3', 
        N'District 4', N'District 5', N'District 6', N'District 7', N'District 8', N'District 9',
        N'District 10', N'District 11', N'District 12', N'Go Vap District', N'Phu Nhuan District', 
        N'Binh Thanh District', N'Tan Binh District', N'Tan Phu District', N'Binh Tan District', 
        N'Binh Chanh District', N'Cu Chi District', N'Hoc Mon District', N'Nha Be District', N'Can Gio District')),
	THOIGIANMOCUA TIME NOT NULL,
	THOIGIANDONGCUA TIME NOT NULL,
	SDT CHAR(10),
	EMAIL VARCHAR(100),
	COBAIDOXE BIT NOT NULL,
	NHANVIENQUANLY CHAR(10),
	
	CONSTRAINT PK_CHINHANH
	PRIMARY KEY (MACHINHANH)
)

-- Bàn ăn được định danh bởi số bàn và mã chi nhánh bàn ăn đặt ở
CREATE TABLE BANAN
(
	SOBAN VARCHAR(3) CHECK (SOBAN NOT LIKE '%[^0-9]%'),
	MACHINHANH CHAR(10),
	VITRI NVARCHAR(50),
	TRANGTHAI NVARCHAR(20) NOT NULL CHECK (TRANGTHAI IN (N'Available', N'Reserved', N'In use', N'Unavailable')),
	SONGUOITOIDA INT NOT NULL,

	CONSTRAINT PK_BANAN
	PRIMARY KEY (SOBAN, MACHINHANH)
)

-- Đặt chỗ định danh bởi mã đặt chỗ
CREATE TABLE DATCHO
(
	MADATCHO CHAR(10),
	NGAYDEN DATE NOT NULL,
	GIODEN TIME NOT NULL,
	SOLUONGKHACH INT NOT NULL,

	GHICHU NVARCHAR(MAX),
	SDT CHAR(10) NOT NULL,

	CONSTRAINT PK_DATCHO
	PRIMARY KEY (MADATCHO)
)

-- Chi tiết đặt chỗ định danh bởi số bàn, mã chi nhánh liên quan, và mã đặt chỗ
CREATE TABLE CHITIETDATCHO
(
	SOBAN VARCHAR(3),
	MACHINHANH CHAR(10),
	MADATCHO CHAR(10),
	SOLUONGKHACH INT,

	CONSTRAINT PK_CHITIETDATCHO
	PRIMARY KEY (SOBAN, MACHINHANH, MADATCHO)
)

-- Nhân viên định danh bởi mã nhân viên
CREATE TABLE NHANVIEN
(
	MANHANVIEN CHAR(10),
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(6) NOT NULL CHECK (GIOITINH IN ('MALE','FEMALE')),
	SDT CHAR(10),
	EMAIL VARCHAR(100),
	DIACHI NVARCHAR(100) NOT NULL,
	CHINHANHLAMVIEC CHAR(10),
	LUONGHIENTAI FLOAT, -- Thuộc tính suy diễn từ LUONG (BOPHAN) và HESOLUONG (LICHSULAMVIEC) của công việc gần nhất
						-- LUONGHIENTAI = LUONG * HESOLUONG
	
	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY (MANHANVIEN)
)

-- Bộ phận định danh bởi mã bộ phận và có thể có nhiều nhân viên
-- lương nhân viên cùng bộ phận tương đối giống nhau
CREATE TABLE BOPHAN
(
	MABOPHAN CHAR(10),
	MACHINHANH CHAR(10),
	TENBOPHAN NVARCHAR(50) NOT NULL,
	LUONG FLOAT NOT NULL,
	QUANLYBOPHAN CHAR(10),

	CONSTRAINT PK_BOPHAN
	PRIMARY KEY (MABOPHAN, MACHINHANH)
)

-- Lịch sử làm việc định danh bởi mã nhân viên, mã bộ phận, và mã chi nhánh làm việc
-- Lịch sử làm việc lưu lại ngày làm, ngày nghỉ, hệ số lương trong khoảng đó của nhân viên
CREATE TABLE LICHSULAMVIEC
(
	MANHANVIEN CHAR(10),
	MABOPHAN CHAR(10),
	MACHINHANH CHAR(10),
	NGAYVAOLAM DATE NOT NULL,
	NGAYNGHIVIEC DATE,
	HESOLUONG FLOAT NOT NULL,

	CONSTRAINT PK_LICHSULAMVIEC
	PRIMARY KEY (MANHANVIEN, MABOPHAN, MACHINHANH)
)

-- Khách hàng định danh bởi mã khách hàng
CREATE TABLE KHACHHANG
(
	MAKHACHHANG CHAR(10),
	HOTEN NVARCHAR(50) NOT NULL,
	SDT CHAR(10),
	EMAIL VARCHAR(100),
	CCCD VARCHAR(20) CHECK (CCCD NOT LIKE '%[^0-9]%'),

	CONSTRAINT PK_KHACHHANNG
	PRIMARY KEY (MAKHACHHANG)
)

-- Đánh giá định danh bởi mã đánh giá
CREATE TABLE DANHGIA
(
	MADANHGIA CHAR(10),
	DIEMPHUCVU INT NOT NULL CHECK (DIEMPHUCVU BETWEEN 1 AND 5),
	DIEMVITRICHINHANH INT NOT NULL CHECK (DIEMVITRICHINHANH BETWEEN 1 AND 5),
	DIEMKHONGGIAN INT NOT NULL CHECK (DIEMKHONGGIAN BETWEEN 1 AND 5),
	BINHLUAN NVARCHAR(MAX),
	KHACHHANGDANHGIA CHAR(10),
	CHINHANH CHAR(10) NOT NULL,
	NHANVIEN CHAR(10),
	MADON CHAR(10),

	CONSTRAINT PK_DANHGIA
	PRIMARY KEY (MADANHGIA)
)

-- Thẻ thành viên định danh bởi mã thẻ
-- Thẻ thành viên chỉ có 3 bản ghi tương ứng với thông tin của 3 phân hạng là Membership, Silver, Gold.
CREATE TABLE THETHANHVIEN
(
	MATHE CHAR(10),
	LOAITHE NVARCHAR(50) NOT NULL CHECK (LOAITHE IN (N'Membership', N'Silver', N'Gold')),

	CONSTRAINT PK_THETHANHVIEN
	PRIMARY KEY (MATHE)
)

-- Chi tiết khách hàng định danh bởi mã khách hàng và mã thẻ
-- Chi tiết khách hàng chứa những thông tin khách hàng liên quan
CREATE TABLE CHITIETKHACHHANG
(
	MAKHACHHANG CHAR(10),
	MATHE CHAR(10),
	NGAYDK DATE NOT NULL,
	DIEMTICHLUY INT NOT NULL CHECK (DIEMTICHLUY >= 0),
	NGAYNANGHANG DATE NOT NULL,
	TRANGTHAITAIKHOAN NVARCHAR(50) NOT NULL CHECK (TRANGTHAITAIKHOAN IN (N'Active', N'Deleted', N'Inactive')), -- N'Hoạt động', N'Đã xoá', N'Tạm dừng'
	NHANVIENTAOLAP CHAR(10) NOT NULL,

	CONSTRAINT PK_CHITIETKHACHHAHG
	PRIMARY KEY (MAKHACHHANG, MATHE)
)

-- Đánh giá món ăn định danh bởi mã đánh giá liên quan và mã món ăn đó
CREATE TABLE DANHGIAMONAN
(
	MADANHGIA CHAR(10),
	MAMON CHAR(10),
	DIEMCHATLUONGMONAN INT NOT NULL CHECK (DIEMCHATLUONGMONAN BETWEEN 1 AND 5),
	DIEMGIACA INT NOT NULL CHECK (DIEMGIACA BETWEEN 1 AND 5),

	CONSTRAINT PK_DANHGIAMONAN
	PRIMARY KEY (MADANHGIA, MAMON)
)

-- Truy cập định danh bởi mã truy cập và mã đánh giá liên quan
CREATE TABLE TRUYCAP
(
	MATRUYCAP CHAR(10),
	MADANHGIA CHAR(10),
	THOIDIEMBATDAU DATE NOT NULL,
	THOIDIEMKETTHUC DATE NOT NULL,

	CONSTRAINT PK_TRUYCAP
	PRIMARY KEY (MATRUYCAP, MADANHGIA)
)

-- Món ăn định nghĩa bởi mã món
CREATE TABLE MONAN
(
	MAMON CHAR(10),
	TENMON NVARCHAR(50) NOT NULL,
	GIAHIENTAI FLOAT NOT NULL,
	DANHMUC NVARCHAR(50) NOT NULL,
	TRANGTHAIPHUCVU NVARCHAR(20) NOT NULL CHECK (TRANGTHAIPHUCVU IN (N'Available', N'Out of stock', N'Discontinued')),

	CONSTRAINT PK_MONAN
	PRIMARY KEY (MAMON)
)

-- Combo món ăn định danh bởi mã combo
-- Combo món ăn có thể chứa nhiều món ăn
CREATE TABLE COMBOMONAN
(
	MACOMBO CHAR(10),
	TENCOMBO NVARCHAR(50) NOT NULL,
	MOTACOMBO NVARCHAR(MAX),
	DONGIACOMBO FLOAT NOT NULL,

	CONSTRAINT PK_COMBOMONAN
	PRIMARY KEY (MACOMBO)
)

-- Chi tiết món ăn định danh bởi mã chi tiết món
-- Chi tiết món ăn định nghĩa rõ ràng một order trong một đơn đặt món
CREATE TABLE CHITIETMONAN
(
	MACTMON CHAR(10),
	MAMON CHAR(10),
	MACOMBO CHAR(10),
	SOLUONG INT NOT NULL,
	GHICHU NVARCHAR(MAX),
	DONGIATONG FLOAT, -- Thuộc tính suy diễn từ SOLUONG (CHITIETMONAN) và GIAHIENTAI (MONAN)/DONGIACOMBO (COMBO)
					  -- DONGIATONG = SOLUONG * GIAHIENTAI/DONGIACOMBO
	MADONDATMON CHAR(10),

	CONSTRAINT PK_CHITIETMONAN
	PRIMARY KEY (MACTMON)
)

-- Món ăn - Combo món ăn định danh bởi mã combo và mã món ăn liên quan
-- Món ăn - Combo món ăn đề ra một combo có những món ăn nào
CREATE TABLE MONAN_COMBOMONAN
(
	MACOMBO CHAR(10),
	MAMON CHAR(10),
	SOLUONG INT NOT NULL,

	CONSTRAINT PK_MONAN_COMBOMONAN
	PRIMARY KEY (MACOMBO, MAMON)
)

-- Khuyến mãi định danh bởi mã khuyến mãi
CREATE TABLE KHUYENMAI
(
	MAKHUYENMAI CHAR(10),
	THONGTINKHUYENMAI NVARCHAR(MAX),
	LOAIKHUYENMAI NVARCHAR(20) NOT NULL,

	CONSTRAINT PK_KHUYENMAI
	PRIMARY KEY (MAKHUYENMAI)
)

-- Khuyến mãi khách hàng định danh bởi mã khuyến mãi
-- Khuyến mãi khách hàng là con của khuyến mãi
-- Khuyến mãi khách hàng dành riêng cho mỗi khách hàng và tính bằng tiền
CREATE TABLE KHUYENMAIKHACHHANG
(
	MAKHUYENMAI CHAR(10),
	TRANGTHAIDUNG BIT NOT NULL,
	MAKHACHHANG CHAR(10) NOT NULL,
	NGAYBATDAU DATE NOT NULL,
	NGAYKETTHUC DATE NOT NULL,
	GIATRITOITHIEU FLOAT NOT NULL,
	LUONGKMTIEN FLOAT NOT NULL,

	CONSTRAINT PK_KHUYENMAIKHACHHANG
	PRIMARY KEY (MAKHUYENMAI)
)

-- Khuyến mãi thẻ thành viên định danh bởi mã khuyến mãi
-- Khuyến mãi thẻ thành viên là con của khuyến mãi
-- Khuyến mãi thẻ thành viên tự động áp dụng cho các khách hàng thuộc mã thẻ loại SILVER, GOLD theo %
CREATE TABLE KHUYENMAITHETHANHVIEN
(
	MAKHUYENMAI CHAR(10),
	MATHE CHAR(10),
	LUONGKMPHANTRAM FLOAT NOT NULL,

	CONSTRAINT PK_KHUYENMAITHETHANHVIEN
	PRIMARY KEY (MAKHUYENMAI)
)

CREATE TABLE MENU 
(
	MACHINHANH CHAR(10),
	MAMON CHAR(10),
	GIAHIENTAI FLOAT,
	TRANGTHAIPHUCVU NVARCHAR(20) NOT NULL CHECK (TRANGTHAIPHUCVU IN (N'Available', N'Out of stock', N'Discontinued')),

	CONSTRAINT PK_MENU
	PRIMARY KEY(MACHINHANH, MAMON)
)

ALTER TABLE MENU
ADD
	CONSTRAINT FK_MENU_CHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_MENU_MONAN
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE

-- Hoá đơn có khoá ngoại đến mã khách hàng và mã chi nhánh liên quan
ALTER TABLE HOADON
ADD
	CONSTRAINT FK_HOADON_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

	CONSTRAINT FK_HOADON_CHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE SET NULL

-- Đơn đặt món có khoá ngoại đến hoá đơn liên quan, khách hàng đặt đơn đó,
-- mã đặt chỗ nếu có, chi nhánh ăn, và nhân viên hỗ trợ
ALTER TABLE DONDATMON
ADD
	CONSTRAINT FK_DONDATMON_HOADON
	FOREIGN KEY (HOADONLIENQUAN)
	REFERENCES HOADON(MAHOADON)
	ON DELETE SET NULL,

	CONSTRAINT FK_DONDATMON_KHACHHANG
	FOREIGN KEY (KHACHHANGDAT)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

    CONSTRAINT FK_DONDATMON_DATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO)
	ON DELETE CASCADE,

    CONSTRAINT FK_DONDATMON_CHINHANH
	FOREIGN KEY (CHINHANHDAT)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_DONDATMON_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL

-- Đặt hàng trực tuyến có khoá ngoại đến mã đơn đặt món
ALTER TABLE DATHANGTRUCTUYEN
ADD
    CONSTRAINT FK_DATHANGTRUCTUYEN_DONDATMON
    FOREIGN KEY (MADHTRUCTUYEN)
    REFERENCES DONDATMON(MADON)

-- Đặt hàng tại chỗ có khoá ngoại đến mã đơn đặt món, số bàn ăn và mã chi nhánh đặt
ALTER TABLE DATHANGTAICHO
ADD
    CONSTRAINT FK_DATHANGTAICHO_DONDATMON
    FOREIGN KEY (MADHTAICHO)
    REFERENCES DONDATMON(MADON),

    CONSTRAINT PK_DATHANGTAICHO_BANAN
    FOREIGN KEY (SOBAN, MACHINHANH)
    REFERENCES BANAN(SOBAN, MACHINHANH)

-- Chi tiết khách hàng khoá ngoại đến mã khách hàng, mã thẻ liên quan, nhân viên tạo lập khách hàng
ALTER TABLE CHITIETKHACHHANG
ADD
	CONSTRAINT FK_CHITIETKHACHHANG_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG),

	CONSTRAINT FK_CHITIETKHACHHANG_THETHANHVIEN
	FOREIGN KEY (MATHE)
	REFERENCES THETHANHVIEN(MATHE),

	CONSTRAINT FK_CHITIETKHACHHANG_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)

-- Đánh giá món ăn có khoá ngoại đến mã đánh giá liên quan và mã món ăn được đánh giá
ALTER TABLE DANHGIAMONAN
ADD
	CONSTRAINT FK_DANHGIAMONAN_DANHGIA
	FOREIGN KEY (MADANHGIA)
	REFERENCES DANHGIA(MADANHGIA)
	ON DELETE CASCADE,

	CONSTRAINT FK_DANHGIAMONAN_MONAN
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE

-- Chi nhánh có khoá ngoại đến nhân viên quản lý chi nhánh
ALTER TABLE CHINHANH
ADD
	CONSTRAINT FK_CHINHANH_NHANVIENQUANLY
	FOREIGN KEY (NHANVIENQUANLY)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL

-- Bàn ăn có khoá ngoại đến mã chi nhánh
ALTER TABLE BANAN
ADD
	CONSTRAINT FK_BANAN_MACHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE

-- Chi tiết đặt chỗ có khoá ngoại đến số bàn, mã chi nhánh, và mã đặt chỗ liên quan
ALTER TABLE CHITIETDATCHO
ADD
	CONSTRAINT FK_CHITIETDATCHO_SOBAN_MACHINHANH
	FOREIGN KEY (SOBAN, MACHINHANH)
	REFERENCES BANAN(SOBAN, MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_CHITIETDATCHO_MADATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO)
	ON DELETE CASCADE

-- Nhân viên khoá ngoại tới mã chi nhánh làm việc
ALTER TABLE NHANVIEN
ADD
	CONSTRAINT FK_NHANVIEN_CHINHANH
	FOREIGN KEY (CHINHANHLAMVIEC)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE NO ACTION

-- Bộ phận khoá ngoại tới mã chi nhánh liên quan, và mã nhân viên quản lý bộ phận liên quan
ALTER TABLE BOPHAN
ADD
	CONSTRAINT FK_BOPHAN_CHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_BOPHAN_NHANVIEN
	FOREIGN KEY (QUANLYBOPHAN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL

-- Lịch sử làm việc khoá ngoại tới mã chi nhánh, mã bộ phận và nhân viên liên quan
ALTER TABLE LICHSULAMVIEC
ADD
	CONSTRAINT FK_LICHSULAMVIEC_BOPHAN
	FOREIGN KEY (MABOPHAN, MACHINHANH)
	REFERENCES BOPHAN(MABOPHAN, MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_LICHSULAMVIEC_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE CASCADE

-- Đánh giá khoá ngoại tới khách hàng đã đánh giá, chi nhánh khách hàng sử dụng,
-- nhân viên liên quan, và mã đơn đặt món có liên quan
ALTER TABLE DANHGIA
ADD
	CONSTRAINT FK_DANHGIA_KHACHHANG
	FOREIGN KEY (KHACHHANGDANHGIA)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

	CONSTRAINT FK_DANHGIA_CHINHANH
	FOREIGN KEY (CHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_DANHGIA_NHANVIEN
	FOREIGN KEY (NHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL,

	CONSTRAINT FK_DANHGIA_DONDATMON
	FOREIGN KEY (MADON)
	REFERENCES DONDATMON(MADON)
	ON DELETE NO ACTION

-- Chi tiết món ăn có khoá ngoại đến món ăn, combo món ăn, và đơn đặt món liên quan
ALTER TABLE CHITIETMONAN
ADD
	CONSTRAINT FK_CHITIETMONAN_MAMON
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE,

	CONSTRAINT FK_CHITIETMONAN_MACOMBO
	FOREIGN KEY (MACOMBO)
	REFERENCES COMBOMONAN(MACOMBO)
	ON DELETE CASCADE,

	CONSTRAINT FK_CHITIETMONAN_DONDATMON
	FOREIGN KEY (MADONDATMON)
	REFERENCES DONDATMON(MADON)
	ON DELETE CASCADE

-- Món ăn - Combo món ăn có khoá ngoại đến mã combo và mã món ăn liên quan combo đó
ALTER TABLE MONAN_COMBOMONAN
ADD
	CONSTRAINT FK_MONAN_COMBOMONAN_MACOMBO
	FOREIGN KEY (MACOMBO)
	REFERENCES COMBOMONAN(MACOMBO)
	ON DELETE CASCADE,

	CONSTRAINT FK_MONAN_COMBOMONAN_MAMON
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE

-- Khuyến mãi khách hàng có khoá ngoại đến mã khuyến mãi và mã khách hàng nhận khuyến mãi
ALTER TABLE KHUYENMAIKHACHHANG
ADD
	CONSTRAINT FK_KHUYENMAIKHACHHANG_MAKHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI)
	ON DELETE CASCADE,

	CONSTRAINT FK_KHUYENMAIKHACHHANG_MAKHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE CASCADE

-- Khuyến mãi thẻ thành viên có khoá ngoại đến mã khuyến mãi và mã thẻ phân hạng liên quan
ALTER TABLE KHUYENMAITHETHANHVIEN
ADD
	CONSTRAINT FK_KHUYENMAITHETHANHVIEN_MAKHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI)
	ON DELETE CASCADE,

	CONSTRAINT FK_KHUYENMAITHETHANHVIEN_MATHE
	FOREIGN KEY (MATHE)
	REFERENCES THETHANHVIEN(MATHE)
	ON DELETE CASCADE

-- Truy cập có khoá ngoại đến mã đánh giá liên quan
ALTER TABLE TRUYCAP
ADD 
	CONSTRAINT FK_TRUYCAP_MADANHGIA
	FOREIGN KEY (MADANHGIA)
	REFERENCES DANHGIA(MADANHGIA)
	ON DELETE CASCADE