ALTER TABLE MENU
ADD
	CONSTRAINT FK_MENU_CHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_MENU_MONAN
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE,

	CONSTRAINT FK_MENU_COMBO
	FOREIGN KEY (MACOMBO)
	REFERENCES COMBOMONAN(MACOMBO)
	ON DELETE CASCADE

-- Hoá đơn có khoá ngoại đến mã khách hàng và mã chi nhánh liên quan
ALTER TABLE HOADON
ADD
	CONSTRAINT FK_HOADON_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

	CONSTRAINT FK_HOADON_CHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE SET NULL

-- Đơn đặt món có khoá ngoại đến hoá đơn liên quan, khách hàng đặt đơn đó,
-- mã đặt chỗ nếu có, chi nhánh ăn, và nhân viên hỗ trợ
ALTER TABLE DONDATMON
ADD
	CONSTRAINT FK_DONDATMON_HOADON
	FOREIGN KEY (HOADONLIENQUAN)
	REFERENCES HOADON(MAHOADON)
	ON DELETE SET NULL,

	CONSTRAINT FK_DONDATMON_KHACHHANG
	FOREIGN KEY (KHACHHANGDAT)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

    CONSTRAINT FK_DONDATMON_DATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO)
	ON DELETE CASCADE,

    CONSTRAINT FK_DONDATMON_CHINHANH
	FOREIGN KEY (CHINHANHDAT)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_DONDATMON_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL

-- Đặt hàng trực tuyến có khoá ngoại đến mã đơn đặt món
ALTER TABLE DATHANGTRUCTUYEN
ADD
    CONSTRAINT FK_DATHANGTRUCTUYEN_DONDATMON
    FOREIGN KEY (MADHTRUCTUYEN)
    REFERENCES DONDATMON(MADON)

-- Đặt hàng tại chỗ có khoá ngoại đến mã đơn đặt món, số bàn ăn và mã chi nhánh đặt
ALTER TABLE DATHANGTAICHO
ADD
    CONSTRAINT FK_DATHANGTAICHO_DONDATMON
    FOREIGN KEY (MADHTAICHO)
    REFERENCES DONDATMON(MADON),

    CONSTRAINT PK_DATHANGTAICHO_BANAN
    FOREIGN KEY (SOBAN, MACHINHANH)
    REFERENCES BANAN(SOBAN, MACHINHANH)

-- Chi tiết khách hàng khoá ngoại đến mã khách hàng, mã thẻ liên quan, nhân viên tạo lập khách hàng
ALTER TABLE CHITIETKHACHHANG
ADD
	CONSTRAINT FK_CHITIETKHACHHANG_KHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG),

	CONSTRAINT FK_CHITIETKHACHHANG_THETHANHVIEN
	FOREIGN KEY (MATHE)
	REFERENCES THETHANHVIEN(MATHE),

	CONSTRAINT FK_CHITIETKHACHHANG_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)

-- Đánh giá món ăn có khoá ngoại đến mã đánh giá liên quan và mã món ăn được đánh giá
ALTER TABLE DANHGIAMONAN
ADD
	CONSTRAINT FK_DANHGIAMONAN_DANHGIA
	FOREIGN KEY (MADANHGIA)
	REFERENCES DANHGIA(MADANHGIA)
	ON DELETE CASCADE,

	CONSTRAINT FK_DANHGIAMONAN_MONAN
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE

-- Chi nhánh có khoá ngoại đến nhân viên quản lý chi nhánh
ALTER TABLE CHINHANH
ADD
	CONSTRAINT FK_CHINHANH_NHANVIENQUANLY
	FOREIGN KEY (NHANVIENQUANLY)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL

-- Bàn ăn có khoá ngoại đến mã chi nhánh
ALTER TABLE BANAN
ADD
	CONSTRAINT FK_BANAN_MACHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE

-- Chi tiết đặt chỗ có khoá ngoại đến số bàn, mã chi nhánh, và mã đặt chỗ liên quan
ALTER TABLE CHITIETDATCHO
ADD
	CONSTRAINT FK_CHITIETDATCHO_SOBAN_MACHINHANH
	FOREIGN KEY (SOBAN, MACHINHANH)
	REFERENCES BANAN(SOBAN, MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_CHITIETDATCHO_MADATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO)
	ON DELETE CASCADE

-- Nhân viên khoá ngoại tới mã chi nhánh làm việc
ALTER TABLE NHANVIEN
ADD
	CONSTRAINT FK_NHANVIEN_CHINHANH
	FOREIGN KEY (CHINHANHLAMVIEC)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE NO ACTION

-- Bộ phận khoá ngoại tới mã chi nhánh liên quan, và mã nhân viên quản lý bộ phận liên quan
ALTER TABLE BOPHAN
ADD
	CONSTRAINT FK_BOPHAN_CHINHANH
	FOREIGN KEY (MACHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_BOPHAN_NHANVIEN
	FOREIGN KEY (QUANLYBOPHAN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL

-- Lịch sử làm việc khoá ngoại tới mã chi nhánh, mã bộ phận và nhân viên liên quan
ALTER TABLE LICHSULAMVIEC
ADD
	CONSTRAINT FK_LICHSULAMVIEC_BOPHAN
	FOREIGN KEY (MABOPHAN, MACHINHANH)
	REFERENCES BOPHAN(MABOPHAN, MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_LICHSULAMVIEC_NHANVIEN
	FOREIGN KEY (MANHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE CASCADE

-- Đánh giá khoá ngoại tới khách hàng đã đánh giá, chi nhánh khách hàng sử dụng,
-- nhân viên liên quan, và mã đơn đặt món có liên quan
ALTER TABLE DANHGIA
ADD
	CONSTRAINT FK_DANHGIA_KHACHHANG
	FOREIGN KEY (KHACHHANGDANHGIA)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE SET NULL,

	CONSTRAINT FK_DANHGIA_CHINHANH
	FOREIGN KEY (CHINHANH)
	REFERENCES CHINHANH(MACHINHANH)
	ON DELETE CASCADE,

	CONSTRAINT FK_DANHGIA_NHANVIEN
	FOREIGN KEY (NHANVIEN)
	REFERENCES NHANVIEN(MANHANVIEN)
	ON DELETE SET NULL,

	CONSTRAINT FK_DANHGIA_DONDATMON
	FOREIGN KEY (MADON)
	REFERENCES DONDATMON(MADON)
	ON DELETE NO ACTION

-- Chi tiết món ăn có khoá ngoại đến món ăn, combo món ăn, và đơn đặt món liên quan
ALTER TABLE CHITIETMONAN
ADD
	CONSTRAINT FK_CHITIETMONAN_MAMON
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE,

	CONSTRAINT FK_CHITIETMONAN_MACOMBO
	FOREIGN KEY (MACOMBO)
	REFERENCES COMBOMONAN(MACOMBO)
	ON DELETE CASCADE,

	CONSTRAINT FK_CHITIETMONAN_DONDATMON
	FOREIGN KEY (MADONDATMON)
	REFERENCES DONDATMON(MADON)
	ON DELETE CASCADE

-- Món ăn - Combo món ăn có khoá ngoại đến mã combo và mã món ăn liên quan combo đó
ALTER TABLE MONAN_COMBOMONAN
ADD
	CONSTRAINT FK_MONAN_COMBOMONAN_MACOMBO
	FOREIGN KEY (MACOMBO)
	REFERENCES COMBOMONAN(MACOMBO)
	ON DELETE CASCADE,

	CONSTRAINT FK_MONAN_COMBOMONAN_MAMON
	FOREIGN KEY (MAMON)
	REFERENCES MONAN(MAMON)
	ON DELETE CASCADE

-- Khuyến mãi khách hàng có khoá ngoại đến mã khuyến mãi và mã khách hàng nhận khuyến mãi
ALTER TABLE KHUYENMAIKHACHHANG
ADD
	CONSTRAINT FK_KHUYENMAIKHACHHANG_MAKHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI)
	ON DELETE CASCADE,

	CONSTRAINT FK_KHUYENMAIKHACHHANG_MAKHACHHANG
	FOREIGN KEY (MAKHACHHANG)
	REFERENCES KHACHHANG(MAKHACHHANG)
	ON DELETE CASCADE

-- Khuyến mãi thẻ thành viên có khoá ngoại đến mã khuyến mãi và mã thẻ phân hạng liên quan
ALTER TABLE KHUYENMAITHETHANHVIEN
ADD
	CONSTRAINT FK_KHUYENMAITHETHANHVIEN_MAKHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI)
	ON DELETE CASCADE,

	CONSTRAINT FK_KHUYENMAITHETHANHVIEN_MATHE
	FOREIGN KEY (MATHE)
	REFERENCES THETHANHVIEN(MATHE)
	ON DELETE CASCADE

-- Truy cập có khoá ngoại đến mã đánh giá liên quan
ALTER TABLE TRUYCAP
ADD 
	CONSTRAINT FK_TRUYCAP_MADANHGIA
	FOREIGN KEY (MADANHGIA)
	REFERENCES DANHGIA(MADANHGIA)
	ON DELETE CASCADE