CREATE DATABASE SushiDB

GO
USE SushiDB
GO
CREATE TABLE HOADON
(
    MAHOADON CHAR(10),
    GIOLAP TIME,
    NGAYLAP DATE,
    VAT FLOAT,
    TIENKHACHDUA FLOAT,
    TRANGTHAI NCHAR(20),
    PHUONGTHUC NCHAR(20),
    BACTHETHANHVIEN CHAR(10),
    MAKHUYENMAI CHAR(10)

    CONSTRAINT PK_HOADON
    PRIMARY KEY MAHOADON
)
CREATE TABLE DONDATMON
(
    MADON CHAR(10),
    GIODAT TIME,
    NGAYDAT DATE,
    TRANGTHAI NCHAR(20),
    HOADONLIENQUAN CHAR(10),
    KHACHHANGDAT CHAR(10),
    MADATCHO CHAR(10),
    CHINHANHDAT CHAR(10), 
    NHANVIENTAOLAP CHAR(10),

    CONSTRAINT PK_DONDATMON
    PRIMARY KEY MADON

)
ALTER TABLE HOADON
ADD
	CONSTRAINT FK_HOADON_THE
	FOREIGN KEY (BACTHETHANHVIEN)
	REFERENCES THETHANHVIEN(MATHE)

	CONSTRAINT FK_HOADON_KHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI)

ALTER TABLE DONDATMON
ADD
	CONSTRAINT FK_DONDATMON_HOADON
	FOREIGN KEY (HOADONLIENQUAN)
	REFERENCES HOADON(MAHOADON)

	CONSTRAINT FK_DONDATMON_KHACHHANG
	FOREIGN KEY (KHACHHANGDAT)
	REFERENCES KHACHHANG(MAKHACHHANG)

    CONSTRAINT FK_DONDATMON_DATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO)

    CONSTRAINT FK_DONDATMON_CHINHANH
	FOREIGN KEY (CHINHANHDAT)
	REFERENCES CHINHANH(MACHINHANH)

	CONSTRAINT FK_DONDATMON_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)