CREATE DATABASE SushiDB

GO
USE SushiDB
GO

CREATE TABLE HOADON
(
    MAHOADON CHAR(10),
    GIOLAP TIME,
    NGAYLAP DATE,
    VAT FLOAT,
    TIENKHACHDUA FLOAT,
    TRANGTHAI NVARCHAR(20),
    PHUONGTHUC NVARCHAR(20),
    BACTHETHANHVIEN CHAR(10),
    MAKHUYENMAI CHAR(10),

	CONSTRAINT PK_HOADON
    PRIMARY KEY (MAHOADON)
)
CREATE TABLE DONDATMON
(
    MADON CHAR(10),
    GIODAT TIME,
    NGAYDAT DATE,
    TRANGTHAI NVARCHAR(20),
    HOADONLIENQUAN CHAR(10),
    KHACHHANGDAT CHAR(10),
    MADATCHO CHAR(10),
    CHINHANHDAT CHAR(10), 
    NHANVIENTAOLAP CHAR(10),

    CONSTRAINT PK_DONDATMON
    PRIMARY KEY (MADON)
)
CREATE TABLE DATHANGTRUCTUYEN
(
    MADHTRUCTUYEN CHAR(10),
    THOIGIANGIAO TIME,
    DIACHIGIAO NVARCHAR(100),
    TRANGTHAI NVARCHAR(20),

    CONSTRAINT PK_DATHANGTRUCTUYEN
    PRIMARY KEY (MADHTRUCTUYEN)
)
CREATE TABLE DATHANGTAICHO
(
    MADHTAICHO CHAR(10),
    MACHINHANH CHAR(10),
    SOBAN CHAR(10),

    CONSTRAINT PK_DATHANGTAICHO
    PRIMARY KEY (MADHTAICHO)
)
CREATE TABLE CHINHANH
(
	MACHINHANH CHAR(10),
	TENCHINHANH NVARCHAR(50),
	DIACHI NVARCHAR(100),
	KHUVUC NVARCHAR(50),
	THOIGIANMOCUA TIME,
	SDT CHAR(10) CHECK (LEN(SDT)=10 AND SDT NOT LIKE '%[^0-9]%'),
	COBAIDOXE BIT,
	NHANVIENQUANLY CHAR(10),
	
	CONSTRAINT PK_CHINHANH
	PRIMARY KEY (MACHINHANH)
)

CREATE TABLE BANAN
(
	SOBAN VARCHAR(3) CHECK (SOBAN NOT LIKE '%[^0-9]%'),
	MACHINHANH CHAR(10),
	VITRI NVARCHAR(50),
	TRANGTHAI NVARCHAR(20),
	SONGUOITOIDA INT,

	CONSTRAINT PK_BANAN
	PRIMARY KEY (SOBAN, MACHINHANH)
)
ALTER TABLE HOADON
ADD
	CONSTRAINT FK_HOADON_THE
	FOREIGN KEY (BACTHETHANHVIEN)
	REFERENCES THETHANHVIEN(MATHE),

	CONSTRAINT FK_HOADON_KHUYENMAI
	FOREIGN KEY (MAKHUYENMAI)
	REFERENCES KHUYENMAI(MAKHUYENMAI)

ALTER TABLE DONDATMON
ADD
	CONSTRAINT FK_DONDATMON_HOADON
	FOREIGN KEY (HOADONLIENQUAN)
	REFERENCES HOADON(MAHOADON),

	CONSTRAINT FK_DONDATMON_KHACHHANG
	FOREIGN KEY (KHACHHANGDAT)
	REFERENCES KHACHHANG(MAKHACHHANG),

    CONSTRAINT FK_DONDATMON_DATCHO
	FOREIGN KEY (MADATCHO)
	REFERENCES DATCHO(MADATCHO),

    CONSTRAINT FK_DONDATMON_CHINHANH
	FOREIGN KEY (CHINHANHDAT)
	REFERENCES CHINHANH(MACHINHANH),

	CONSTRAINT FK_DONDATMON_NHANVIEN
	FOREIGN KEY (NHANVIENTAOLAP)
	REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE DATHANGTRUCTUYEN
ADD
    CONSTRAINT PK_DATHANGTRUCTUYEN_DONDATMON
    FOREIGN KEY (MADHTRUCTUYEN)
    REFERENCES DONDATMON(MADON)

ALTER TABLE DATHANGTAICHO
ADD
    CONSTRAINT PK_DATHANGTAICHO_DONDATMON
    FOREIGN KEY (MADHTAICHO)
    REFERENCES DONDATMON(MADON),

    CONSTRAINT PK_DATHANGTAICHO_CHINHANH
    FOREIGN KEY (MACHINHANH)
    REFERENCES CHINHANH(MACHINHANH),

    CONSTRAINT PK_DATHANGTAICHO_SOBAN
    FOREIGN KEY (SOBAN)
    REFERENCES SOBAN(SOBAN)
