USE SUSHIDB
GO


-- Truy vấn A: Cấp và cập nhật thông tin thẻ cho khách hàng
SET STATISTICS TIME ON;
EXEC SP_TaoVaCapThe 'KH00000501', N'Tran Dan Huy', '0913958295', 'danhuy@gmail.com', '059284823324', 'NV00000001'
SET STATISTICS TIME OFF;
GO

-- Chỉ mục cho cột MAKHACHHANG trong bảng KHACHHANG để kiểm tra sự tồn tại và thực hiện INSERT
CREATE NONCLUSTERED INDEX IDX_KHACHHANG_MAKHACHHANG ON KHACHHANG(MAKHACHHANG);

-- Chỉ mục cho cột NHANVIENTAOLAP trong bảng CHITIETKHACHHANG để tối ưu hóa câu lệnh UPDATE
CREATE NONCLUSTERED INDEX IDX_CHITIETKHACHHANG_NHANVIENTAOLAP ON CHITIETKHACHHANG(NHANVIENTAOLAP);


-- Truy vấn B: Kiểm tra và cập nhật hạng thẻ 
SET STATISTICS TIME ON;
EXEC SP_CapNhatHangThe
SET STATISTICS TIME OFF;
GO

-- Chỉ mục cho các cột được sử dụng trong mệnh đề WHERE
CREATE NONCLUSTERED INDEX IDX_CHITIETKHACHHANG_NGAYNANGHANG ON CHITIETKHACHHANG(NGAYNANGHANG);

-- Chỉ mục cho các cột được sử dụng trong JOIN
CREATE NONCLUSTERED INDEX IDX_CHITIETKHACHHANG_MATHE ON CHITIETKHACHHANG(MATHE);

-- Chỉ mục cho cột MAKHACHHANG để tối ưu hóa điều kiện trong UPDATE
CREATE NONCLUSTERED INDEX IDX_CHITIETKHACHHANG_MAKHACHHANG ON CHITIETKHACHHANG(MAKHACHHANG);

-- Chỉ mục cho cột DIEMTICHLUY được sử dụng trong điều kiện IF
CREATE NONCLUSTERED INDEX IDX_CHITIETKHACHHANG_DIEMTICHLUY ON CHITIETKHACHHANG(DIEMTICHLUY);
GO


-- Truy vấn C: Danh sách các hóa đơn và đơn đặt món theo ngày cụ thể
SET STATISTICS TIME ON;
EXEC SP_DS_DONDATMON_HOADON_THEONGAY @ngaydat = '2024-12-17'
SET STATISTICS TIME OFF;
GO

-- Chỉ mục cho cột HOADONLIENQUAN trong bảng DONDATMON để tối ưu hóa JOIN với HOADON
CREATE NONCLUSTERED INDEX IDX_DONDATMON_HOADONLIENQUAN ON DONDATMON(HOADONLIENQUAN);
GO


-- Truy vấn D: Danh sách theo dõi xu hướng của các khách hàng khi lựa chọn loại đặt hàng tại một chi nhánh trong một khoảng thời gian
SET STATISTICS TIME ON;
EXEC SP_THONGKE_XUHUONG_KHACHHANG @ngayBatDau = '2024-12-12', @ngayKetThuc = '2025-1-12', @maChiNhanh = 'CN00000001'
SET STATISTICS TIME OFF;
GO


-- Truy vấn E: Xem danh sách nhân viên và đánh giá tương ứng với mỗi nhân viên đó
SET STATISTICS TIME ON;
EXEC SP_XemDanhSachDanhGiaNhanVien;
SET STATISTICS TIME OFF;
GO

-- Tạo chỉ mục cho thuộc tính CHINHANHLAMVIEC trong bảng NHANVIEN (sử dụng trong JOIN và GROUP BY)
CREATE NONCLUSTERED INDEX IDX_NHANVIEN_CHINHANHLAMVIEC ON NHANVIEN(CHINHANHLAMVIEC);

-- Tạo chỉ mục cho thuộc tính NHANVIEN trong bảng DANHGIA (sử dụng trong JOIN)
CREATE NONCLUSTERED INDEX IDX_DANHGIA_NHANVIEN ON DANHGIA(NHANVIEN);

-- Tạo chỉ mục cho thuộc tính DIEMPHUCVU trong bảng DANHGIA (sử dụng trong AVG)
CREATE NONCLUSTERED INDEX IDX_DANHGIA_DIEMPHUCVU ON DANHGIA(DIEMPHUCVU);

-- Tạo chỉ mục cho thuộc tính DIEMVITRICHINHANH trong bảng DANHGIA (sử dụng trong AVG)
CREATE NONCLUSTERED INDEX IDX_DANHGIA_DIEMVITRICHINHANH ON DANHGIA(DIEMVITRICHINHANH);

-- Tạo chỉ mục cho thuộc tính DIEMKHONGGIAN trong bảng DANHGIA (sử dụng trong AVG)
CREATE NONCLUSTERED INDEX IDX_DANHGIA_DIEMKHONGGIAN ON DANHGIA(DIEMKHONGGIAN);
GO


-- Truy vấn F: Thống kê chất lượng món ăn và đánh giá của khách hàng
SET STATISTICS TIME ON;
EXEC SP_THONGKE_CHATLUONG_MONAN @NGAYBATDAU = '2024-01-01';
SET STATISTICS TIME OFF;
GO

-- Chỉ mục cho cột NGAYDAT trong bảng DONDATMON để lọc theo ngày
CREATE NONCLUSTERED INDEX IDX_DONDATMON_NGAYDAT ON DONDATMON(NGAYDAT);

-- Tạo chỉ mục cho thuộc tính DIEMCHATLUONGMONAN trong bảng DANHGIAMONAN (sử dụng trong AVG)
CREATE NONCLUSTERED INDEX IDX_DANHGIA_DIEMCHATLUONGMONAN ON DANHGIAMONAN(DIEMCHATLUONGMONAN);

-- Tạo chỉ mục cho thuộc tính DIEMGIACA trong bảng DANHGIAMONAN (sử dụng trong AVG)
CREATE NONCLUSTERED INDEX IDX_DANHGIA_DIEMGIACA ON DANHGIAMONAN(DIEMGIACA);
GO


-- Truy vấn G: Tính toán tổng tiền trước và sau khuyến mãi, sau đó cập nhật theo mã hóa đơn.
SET STATISTICS TIME ON;
EXEC SP_TinhVaCapNhatTongTien 'HD00000001'
SET STATISTICS TIME OFF;
GO

-- Kiểm tra
SELECT * FROM HOADON WHERE MAHOADON = 'HD00000001'
SELECT * FROM DONDATMON WHERE HOADONLIENQUAN = 'HD00000001'
GO

-- Chỉ mục cho bảng KHUYENMAIKHACHHANG để lọc khuyến mãi theo MAKHACHHANG
CREATE NONCLUSTERED INDEX IDX_KHUYENMAIKHACHHANG_MAKHACHHANG ON KHUYENMAIKHACHHANG (MAKHACHHANG, LUONGKMTIEN);

-- Chỉ mục cho bảng KHUYENMAITHETHANHVIEN để lọc khuyến mãi theo MATHE
CREATE NONCLUSTERED INDEX IDX_KHUYENMAITHETHANHVIEN_MATHE ON KHUYENMAITHETHANHVIEN (MATHE, LUONGKMPHANTRAM);
GO


-- Truy vấn H: Thống kê doanh thu của một chi nhánh trong khoảng thời gian
SET STATISTICS TIME ON;
EXEC sp_ThongKeDoanhThu 'CN00000002', '2024-01-01', '2024-11-29'
SET STATISTICS TIME OFF;
GO

-- Tạo chỉ mục non-clustered trên NgayLap trong bảng HOADON
CREATE NONCLUSTERED INDEX IDX_HOADON_NGAYLAP ON HOADON (NGAYLAP);

-- Tạo chỉ mục non-clustered trên MaChiNhanh trong bảng HOADON
CREATE NONCLUSTERED INDEX IDX_HOADON_MACHINHANH ON HOADON (MACHINHANH);


-- Truy vấn I: Thống kê những món ăn đắt hàng nhất về số lượng trong khoảng thời gian nhất định
SET STATISTICS TIME ON;
EXEC SP_THONGKE_TOP_MONAN '2024-05-07', '2030-12-31', 10;
SET STATISTICS TIME OFF;
GO

-- Tạo chỉ mục non-clustered trên MaMon trong bảng MENU
CREATE NONCLUSTERED INDEX IDX_MENU_MAMON ON MENU(MAMON);


-- Truy vấn J: Thống kê những khách hàng mang lại doanh thu cao nhất trong khoảng thời gian nhất định
SET STATISTICS TIME ON;
EXEC SP_ThongKe_Top_KhachHang '2000-01-01', '2024-12-31', 5;
SET STATISTICS TIME OFF;
GO

-- Tạo chỉ mục non-clustered trên MaKhachHang trong bảng HOADON
CREATE NONCLUSTERED INDEX IDX_HOADON_MAKHACHHANG ON HOADON (MAKHACHHANG);