BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[User] (
    [id] INT NOT NULL IDENTITY(1,1),
    [username] NVARCHAR(1000) NOT NULL,
    [password] NVARCHAR(1000) NOT NULL,
    [email] NVARCHAR(1000) NOT NULL,
    [role] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [User_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [User_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [User_username_key] UNIQUE NONCLUSTERED ([username]),
    CONSTRAINT [User_email_key] UNIQUE NONCLUSTERED ([email])
);

-- CreateTable
CREATE TABLE [dbo].[BANAN] (
    [SOBAN] VARCHAR(3) NOT NULL,
    [MACHINHANH] CHAR(10) NOT NULL,
    [VITRI] NVARCHAR(50),
    [TRANGTHAI] NVARCHAR(20) NOT NULL,
    [SONGUOITOIDA] INT NOT NULL,
    CONSTRAINT [PK_BANAN] PRIMARY KEY CLUSTERED ([SOBAN],[MACHINHANH])
);

-- CreateTable
CREATE TABLE [dbo].[BOPHAN] (
    [MABOPHAN] CHAR(10) NOT NULL,
    [MACHINHANH] CHAR(10) NOT NULL,
    [TENBOPHAN] NVARCHAR(50) NOT NULL,
    [LUONG] FLOAT(53) NOT NULL,
    [QUANLYBOPHAN] CHAR(10),
    CONSTRAINT [PK_BOPHAN] PRIMARY KEY CLUSTERED ([MABOPHAN],[MACHINHANH])
);

-- CreateTable
CREATE TABLE [dbo].[CHINHANH] (
    [MACHINHANH] CHAR(10) NOT NULL,
    [TENCHINHANH] NVARCHAR(50) NOT NULL,
    [DIACHI] NVARCHAR(100) NOT NULL,
    [KHUVUC] NVARCHAR(50) NOT NULL,
    [THOIGIANMOCUA] TIME NOT NULL,
    [THOIGIANDONGCUA] TIME NOT NULL,
    [SDT] CHAR(10),
    [EMAIL] VARCHAR(100),
    [COBAIDOXE] BIT NOT NULL,
    [NHANVIENQUANLY] CHAR(10),
    CONSTRAINT [PK_CHINHANH] PRIMARY KEY CLUSTERED ([MACHINHANH])
);

-- CreateTable
CREATE TABLE [dbo].[CHITIETDATCHO] (
    [SOBAN] VARCHAR(3) NOT NULL,
    [MACHINHANH] CHAR(10) NOT NULL,
    [MADATCHO] CHAR(10) NOT NULL,
    [SOLUONGKHACH] INT,
    CONSTRAINT [PK_CHITIETDATCHO] PRIMARY KEY CLUSTERED ([SOBAN],[MACHINHANH],[MADATCHO])
);

-- CreateTable
CREATE TABLE [dbo].[CHITIETKHACHHANG] (
    [MAKHACHHANG] CHAR(10) NOT NULL,
    [MATHE] CHAR(10) NOT NULL,
    [NGAYDK] DATE NOT NULL,
    [DIEMTICHLUY] INT NOT NULL,
    [NGAYNANGHANG] DATE NOT NULL,
    [TRANGTHAITAIKHOAN] NVARCHAR(50) NOT NULL,
    [NHANVIENTAOLAP] CHAR(10) NOT NULL,
    CONSTRAINT [PK_CHITIETKHACHHAHG] PRIMARY KEY CLUSTERED ([MAKHACHHANG],[MATHE])
);

-- CreateTable
CREATE TABLE [dbo].[CHITIETMONAN] (
    [MACTMON] CHAR(10) NOT NULL,
    [MAMENU] CHAR(10),
    [SOLUONG] INT NOT NULL,
    [GHICHU] NVARCHAR(max),
    [DONGIATONG] FLOAT(53),
    [MADONDATMON] CHAR(10),
    CONSTRAINT [PK_CHITIETMONAN] PRIMARY KEY CLUSTERED ([MACTMON])
);

-- CreateTable
CREATE TABLE [dbo].[COMBOMONAN] (
    [MACOMBO] CHAR(10) NOT NULL,
    [TENCOMBO] NVARCHAR(50) NOT NULL,
    [MOTACOMBO] NVARCHAR(max),
    CONSTRAINT [PK_COMBOMONAN] PRIMARY KEY CLUSTERED ([MACOMBO])
);

-- CreateTable
CREATE TABLE [dbo].[DANHGIA] (
    [MADANHGIA] CHAR(10) NOT NULL,
    [DIEMPHUCVU] INT NOT NULL,
    [DIEMVITRICHINHANH] INT NOT NULL,
    [DIEMKHONGGIAN] INT NOT NULL,
    [BINHLUAN] NVARCHAR(max),
    [KHACHHANGDANHGIA] CHAR(10),
    [CHINHANH] CHAR(10) NOT NULL,
    [NHANVIEN] CHAR(10),
    [MADON] CHAR(10),
    CONSTRAINT [PK_DANHGIA] PRIMARY KEY CLUSTERED ([MADANHGIA])
);

-- CreateTable
CREATE TABLE [dbo].[DANHGIAMONAN] (
    [MADANHGIA] CHAR(10) NOT NULL,
    [MAMON] CHAR(10) NOT NULL,
    [DIEMCHATLUONGMONAN] INT NOT NULL,
    [DIEMGIACA] INT NOT NULL,
    CONSTRAINT [PK_DANHGIAMONAN] PRIMARY KEY CLUSTERED ([MADANHGIA],[MAMON])
);

-- CreateTable
CREATE TABLE [dbo].[DATCHO] (
    [MADATCHO] CHAR(10) NOT NULL,
    [NGAYDEN] DATE NOT NULL,
    [GIODEN] TIME NOT NULL,
    [SOLUONGKHACH] INT NOT NULL,
    [GHICHU] NVARCHAR(max),
    [SDT] CHAR(10) NOT NULL,
    CONSTRAINT [PK_DATCHO] PRIMARY KEY CLUSTERED ([MADATCHO])
);

-- CreateTable
CREATE TABLE [dbo].[DATHANGTAICHO] (
    [MADHTAICHO] CHAR(10) NOT NULL,
    [MACHINHANH] CHAR(10),
    [SOBAN] VARCHAR(3),
    CONSTRAINT [PK_DATHANGTAICHO] PRIMARY KEY CLUSTERED ([MADHTAICHO])
);

-- CreateTable
CREATE TABLE [dbo].[DATHANGTRUCTUYEN] (
    [MADHTRUCTUYEN] CHAR(10) NOT NULL,
    [THOIGIANGIAO] TIME NOT NULL,
    [DIACHIGIAO] NVARCHAR(100) NOT NULL,
    [TRANGTHAIGIAO] NVARCHAR(20) NOT NULL,
    CONSTRAINT [PK_DATHANGTRUCTUYEN] PRIMARY KEY CLUSTERED ([MADHTRUCTUYEN])
);

-- CreateTable
CREATE TABLE [dbo].[DONDATMON] (
    [MADON] CHAR(10) NOT NULL,
    [GIODAT] TIME NOT NULL,
    [NGAYDAT] DATE NOT NULL,
    [TRANGTHAI] NVARCHAR(20) NOT NULL,
    [LOAIDONDATMON] NVARCHAR(20) NOT NULL,
    [HOADONLIENQUAN] CHAR(10),
    [KHACHHANGDAT] CHAR(10),
    [MADATCHO] CHAR(10),
    [CHINHANHDAT] CHAR(10) NOT NULL,
    [NHANVIENTAOLAP] CHAR(10),
    [THANHTIEN] FLOAT(53),
    CONSTRAINT [PK_DONDATMON] PRIMARY KEY CLUSTERED ([MADON])
);

-- CreateTable
CREATE TABLE [dbo].[HOADON] (
    [MAHOADON] CHAR(10) NOT NULL,
    [GIOLAP] TIME NOT NULL,
    [NGAYLAP] DATE NOT NULL,
    [VAT] FLOAT(53) CONSTRAINT [DF__HOADON__VAT__656C112C] DEFAULT 0.08,
    [TIENKHACHDUA] FLOAT(53) NOT NULL,
    [TRANGTHAI] NVARCHAR(20) NOT NULL,
    [PHUONGTHUC] NVARCHAR(20) NOT NULL,
    [MAKHACHHANG] CHAR(10),
    [MACHINHANH] CHAR(10),
    [TONGTIENTRUOCKM] FLOAT(53),
    [TONGTIENSAUKM] FLOAT(53),
    CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED ([MAHOADON])
);

-- CreateTable
CREATE TABLE [dbo].[KHACHHANG] (
    [MAKHACHHANG] CHAR(10) NOT NULL,
    [HOTEN] NVARCHAR(50) NOT NULL,
    [SDT] CHAR(10),
    [EMAIL] VARCHAR(100),
    [CCCD] VARCHAR(20),
    CONSTRAINT [PK_KHACHHANNG] PRIMARY KEY CLUSTERED ([MAKHACHHANG])
);

-- CreateTable
CREATE TABLE [dbo].[KHUYENMAI] (
    [MAKHUYENMAI] CHAR(10) NOT NULL,
    [THONGTINKHUYENMAI] NVARCHAR(max),
    [LOAIKHUYENMAI] NVARCHAR(20) NOT NULL,
    CONSTRAINT [PK_KHUYENMAI] PRIMARY KEY CLUSTERED ([MAKHUYENMAI])
);

-- CreateTable
CREATE TABLE [dbo].[KHUYENMAIKHACHHANG] (
    [MAKHUYENMAI] CHAR(10) NOT NULL,
    [TRANGTHAIDUNG] BIT NOT NULL,
    [MAKHACHHANG] CHAR(10),
    [NGAYBATDAU] DATE NOT NULL,
    [NGAYKETTHUC] DATE NOT NULL,
    [GIATRITOITHIEU] FLOAT(53) NOT NULL,
    [LUONGKMTIEN] FLOAT(53) NOT NULL,
    CONSTRAINT [PK_KHUYENMAIKHACHHANG] PRIMARY KEY CLUSTERED ([MAKHUYENMAI])
);

-- CreateTable
CREATE TABLE [dbo].[KHUYENMAITHETHANHVIEN] (
    [MAKHUYENMAI] CHAR(10) NOT NULL,
    [MATHE] CHAR(10),
    [LUONGKMPHANTRAM] FLOAT(53) NOT NULL,
    CONSTRAINT [PK_KHUYENMAITHETHANHVIEN] PRIMARY KEY CLUSTERED ([MAKHUYENMAI])
);

-- CreateTable
CREATE TABLE [dbo].[LICHSULAMVIEC] (
    [MANHANVIEN] CHAR(10) NOT NULL,
    [MABOPHAN] CHAR(10) NOT NULL,
    [MACHINHANH] CHAR(10) NOT NULL,
    [NGAYVAOLAM] DATE NOT NULL,
    [NGAYNGHIVIEC] DATE,
    [HESOLUONG] FLOAT(53) NOT NULL,
    CONSTRAINT [PK_LICHSULAMVIEC] PRIMARY KEY CLUSTERED ([MANHANVIEN],[MABOPHAN],[MACHINHANH])
);

-- CreateTable
CREATE TABLE [dbo].[MENU] (
    [MAMENU] CHAR(10) NOT NULL,
    [MACHINHANH] CHAR(10),
    [MAMON] CHAR(10),
    [MACOMBO] CHAR(10),
    [GIAHIENTAI] FLOAT(53),
    [TRANGTHAIPHUCVU] NVARCHAR(20) NOT NULL,
    CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED ([MAMENU])
);

-- CreateTable
CREATE TABLE [dbo].[MONAN] (
    [MAMON] CHAR(10) NOT NULL,
    [TENMON] NVARCHAR(50) NOT NULL,
    [DANHMUC] NVARCHAR(50) NOT NULL,
    CONSTRAINT [PK_MONAN] PRIMARY KEY CLUSTERED ([MAMON])
);

-- CreateTable
CREATE TABLE [dbo].[MONAN_COMBOMONAN] (
    [MACOMBO] CHAR(10) NOT NULL,
    [MAMON] CHAR(10) NOT NULL,
    [SOLUONG] INT NOT NULL,
    CONSTRAINT [PK_MONAN_COMBOMONAN] PRIMARY KEY CLUSTERED ([MACOMBO],[MAMON])
);

-- CreateTable
CREATE TABLE [dbo].[NHANVIEN] (
    [MANHANVIEN] CHAR(10) NOT NULL,
    [HOTEN] NVARCHAR(50) NOT NULL,
    [NGAYSINH] DATE NOT NULL,
    [GIOITINH] NVARCHAR(6) NOT NULL,
    [SDT] CHAR(10),
    [EMAIL] VARCHAR(100),
    [DIACHI] NVARCHAR(100) NOT NULL,
    [CHINHANHLAMVIEC] CHAR(10),
    [LUONGHIENTAI] FLOAT(53),
    CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED ([MANHANVIEN])
);

-- CreateTable
CREATE TABLE [dbo].[THETHANHVIEN] (
    [MATHE] CHAR(10) NOT NULL,
    [LOAITHE] NVARCHAR(50) NOT NULL,
    CONSTRAINT [PK_THETHANHVIEN] PRIMARY KEY CLUSTERED ([MATHE])
);

-- CreateTable
CREATE TABLE [dbo].[TRUYCAP] (
    [MATRUYCAP] CHAR(10) NOT NULL,
    [MADHTRUCTUYEN] CHAR(10) NOT NULL,
    [THOIDIEMBATDAU] DATE NOT NULL,
    [THOIDIEMKETTHUC] DATE NOT NULL,
    CONSTRAINT [PK_TRUYCAP] PRIMARY KEY CLUSTERED ([MATRUYCAP],[MADHTRUCTUYEN])
);

-- AddForeignKey
ALTER TABLE [dbo].[BANAN] ADD CONSTRAINT [FK_BANAN_MACHINHANH] FOREIGN KEY ([MACHINHANH]) REFERENCES [dbo].[CHINHANH]([MACHINHANH]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[BOPHAN] ADD CONSTRAINT [FK_BOPHAN_CHINHANH] FOREIGN KEY ([MACHINHANH]) REFERENCES [dbo].[CHINHANH]([MACHINHANH]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[BOPHAN] ADD CONSTRAINT [FK_BOPHAN_NHANVIEN] FOREIGN KEY ([QUANLYBOPHAN]) REFERENCES [dbo].[NHANVIEN]([MANHANVIEN]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHINHANH] ADD CONSTRAINT [FK_CHINHANH_NHANVIENQUANLY] FOREIGN KEY ([NHANVIENQUANLY]) REFERENCES [dbo].[NHANVIEN]([MANHANVIEN]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHITIETDATCHO] ADD CONSTRAINT [FK_CHITIETDATCHO_MADATCHO] FOREIGN KEY ([MADATCHO]) REFERENCES [dbo].[DATCHO]([MADATCHO]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHITIETDATCHO] ADD CONSTRAINT [FK_CHITIETDATCHO_SOBAN_MACHINHANH] FOREIGN KEY ([SOBAN], [MACHINHANH]) REFERENCES [dbo].[BANAN]([SOBAN],[MACHINHANH]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHITIETKHACHHANG] ADD CONSTRAINT [FK_CHITIETKHACHHANG_KHACHHANG] FOREIGN KEY ([MAKHACHHANG]) REFERENCES [dbo].[KHACHHANG]([MAKHACHHANG]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHITIETKHACHHANG] ADD CONSTRAINT [FK_CHITIETKHACHHANG_NHANVIEN] FOREIGN KEY ([NHANVIENTAOLAP]) REFERENCES [dbo].[NHANVIEN]([MANHANVIEN]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHITIETKHACHHANG] ADD CONSTRAINT [FK_CHITIETKHACHHANG_THETHANHVIEN] FOREIGN KEY ([MATHE]) REFERENCES [dbo].[THETHANHVIEN]([MATHE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHITIETMONAN] ADD CONSTRAINT [FK_CHITIETMONAN_DONDATMON] FOREIGN KEY ([MADONDATMON]) REFERENCES [dbo].[DONDATMON]([MADON]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[CHITIETMONAN] ADD CONSTRAINT [FK_CHITIETMONAN_MAMENU] FOREIGN KEY ([MAMENU]) REFERENCES [dbo].[MENU]([MAMENU]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DANHGIA] ADD CONSTRAINT [FK_DANHGIA_CHINHANH] FOREIGN KEY ([CHINHANH]) REFERENCES [dbo].[CHINHANH]([MACHINHANH]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DANHGIA] ADD CONSTRAINT [FK_DANHGIA_DONDATMON] FOREIGN KEY ([MADON]) REFERENCES [dbo].[DONDATMON]([MADON]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DANHGIA] ADD CONSTRAINT [FK_DANHGIA_KHACHHANG] FOREIGN KEY ([KHACHHANGDANHGIA]) REFERENCES [dbo].[KHACHHANG]([MAKHACHHANG]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DANHGIA] ADD CONSTRAINT [FK_DANHGIA_NHANVIEN] FOREIGN KEY ([NHANVIEN]) REFERENCES [dbo].[NHANVIEN]([MANHANVIEN]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DANHGIAMONAN] ADD CONSTRAINT [FK_DANHGIAMONAN_DANHGIA] FOREIGN KEY ([MADANHGIA]) REFERENCES [dbo].[DANHGIA]([MADANHGIA]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DANHGIAMONAN] ADD CONSTRAINT [FK_DANHGIAMONAN_MONAN] FOREIGN KEY ([MAMON]) REFERENCES [dbo].[MONAN]([MAMON]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DATHANGTAICHO] ADD CONSTRAINT [FK_DATHANGTAICHO_DONDATMON] FOREIGN KEY ([MADHTAICHO]) REFERENCES [dbo].[DONDATMON]([MADON]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DATHANGTAICHO] ADD CONSTRAINT [PK_DATHANGTAICHO_BANAN] FOREIGN KEY ([SOBAN], [MACHINHANH]) REFERENCES [dbo].[BANAN]([SOBAN],[MACHINHANH]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DATHANGTRUCTUYEN] ADD CONSTRAINT [FK_DATHANGTRUCTUYEN_DONDATMON] FOREIGN KEY ([MADHTRUCTUYEN]) REFERENCES [dbo].[DONDATMON]([MADON]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DONDATMON] ADD CONSTRAINT [FK_DONDATMON_CHINHANH] FOREIGN KEY ([CHINHANHDAT]) REFERENCES [dbo].[CHINHANH]([MACHINHANH]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DONDATMON] ADD CONSTRAINT [FK_DONDATMON_DATCHO] FOREIGN KEY ([MADATCHO]) REFERENCES [dbo].[DATCHO]([MADATCHO]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DONDATMON] ADD CONSTRAINT [FK_DONDATMON_HOADON] FOREIGN KEY ([HOADONLIENQUAN]) REFERENCES [dbo].[HOADON]([MAHOADON]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DONDATMON] ADD CONSTRAINT [FK_DONDATMON_KHACHHANG] FOREIGN KEY ([KHACHHANGDAT]) REFERENCES [dbo].[KHACHHANG]([MAKHACHHANG]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[DONDATMON] ADD CONSTRAINT [FK_DONDATMON_NHANVIEN] FOREIGN KEY ([NHANVIENTAOLAP]) REFERENCES [dbo].[NHANVIEN]([MANHANVIEN]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[HOADON] ADD CONSTRAINT [FK_HOADON_CHINHANH] FOREIGN KEY ([MACHINHANH]) REFERENCES [dbo].[CHINHANH]([MACHINHANH]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[HOADON] ADD CONSTRAINT [FK_HOADON_KHACHHANG] FOREIGN KEY ([MAKHACHHANG]) REFERENCES [dbo].[KHACHHANG]([MAKHACHHANG]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[KHUYENMAIKHACHHANG] ADD CONSTRAINT [FK_KHUYENMAIKHACHHANG_MAKHACHHANG] FOREIGN KEY ([MAKHACHHANG]) REFERENCES [dbo].[KHACHHANG]([MAKHACHHANG]) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[KHUYENMAIKHACHHANG] ADD CONSTRAINT [FK_KHUYENMAIKHACHHANG_MAKHUYENMAI] FOREIGN KEY ([MAKHUYENMAI]) REFERENCES [dbo].[KHUYENMAI]([MAKHUYENMAI]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[KHUYENMAITHETHANHVIEN] ADD CONSTRAINT [FK_KHUYENMAITHETHANHVIEN_MAKHUYENMAI] FOREIGN KEY ([MAKHUYENMAI]) REFERENCES [dbo].[KHUYENMAI]([MAKHUYENMAI]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[KHUYENMAITHETHANHVIEN] ADD CONSTRAINT [FK_KHUYENMAITHETHANHVIEN_MATHE] FOREIGN KEY ([MATHE]) REFERENCES [dbo].[THETHANHVIEN]([MATHE]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[LICHSULAMVIEC] ADD CONSTRAINT [FK_LICHSULAMVIEC_BOPHAN] FOREIGN KEY ([MABOPHAN], [MACHINHANH]) REFERENCES [dbo].[BOPHAN]([MABOPHAN],[MACHINHANH]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[LICHSULAMVIEC] ADD CONSTRAINT [FK_LICHSULAMVIEC_NHANVIEN] FOREIGN KEY ([MANHANVIEN]) REFERENCES [dbo].[NHANVIEN]([MANHANVIEN]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[MENU] ADD CONSTRAINT [FK_MENU_CHINHANH] FOREIGN KEY ([MACHINHANH]) REFERENCES [dbo].[CHINHANH]([MACHINHANH]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[MENU] ADD CONSTRAINT [FK_MENU_COMBO] FOREIGN KEY ([MACOMBO]) REFERENCES [dbo].[COMBOMONAN]([MACOMBO]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[MENU] ADD CONSTRAINT [FK_MENU_MONAN] FOREIGN KEY ([MAMON]) REFERENCES [dbo].[MONAN]([MAMON]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[MONAN_COMBOMONAN] ADD CONSTRAINT [FK_MONAN_COMBOMONAN_MACOMBO] FOREIGN KEY ([MACOMBO]) REFERENCES [dbo].[COMBOMONAN]([MACOMBO]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[MONAN_COMBOMONAN] ADD CONSTRAINT [FK_MONAN_COMBOMONAN_MAMON] FOREIGN KEY ([MAMON]) REFERENCES [dbo].[MONAN]([MAMON]) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[NHANVIEN] ADD CONSTRAINT [FK_NHANVIEN_CHINHANH] FOREIGN KEY ([CHINHANHLAMVIEC]) REFERENCES [dbo].[CHINHANH]([MACHINHANH]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TRUYCAP] ADD CONSTRAINT [FK_TRUYCAP_MADHTRUCTUYEN] FOREIGN KEY ([MADHTRUCTUYEN]) REFERENCES [dbo].[DATHANGTRUCTUYEN]([MADHTRUCTUYEN]) ON DELETE CASCADE ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
